---
- hosts: all
  user: ansible
  become: yes

  tasks:
    - name: "create bashrc file or set permission"
      shell: "test -f $HOME/.bashrc || touch $HOME/.bashrc && chmod 600 $HOME/.bashrc"
      
    - name: "add line to $HOME/.bashrc"
      lineinfile:
        dest: "$HOME/.bashrc"
        line: "export EDITOR=/bin/vi"
        state: "present"
        backup: "yes"
        
    - name: "add line to /etc/bashrc"
      lineinfile:
        dest: "/etc/bashrc"
        line: "export EDITOR=/bin/vi"
        state: "present"
        backup: "yes"
        
    - name: "add line to /etc/profile"
      lineinfile:
        dest: "/etc/profile"
        line: "export EDITOR=/bin/vi"
        state: "present"
        backup: "yes"
