---
- hosts: all
  user: ansible
  become: yes

  tasks:
    - name: "create bashrc file"
      shell: "test -f /.bashrc || touch /.bashrc && chmod 600 /.bashrc"
      
    - name: "add line to /.bashrc"
      lineinfile:
        dest: "/.bashrc"
        line: "export EDITOR=/bin/vi"
        state: "present"
        backup: "yes"
        
    - name: "add line to /etc/bashrc"
      lineinfile:
        dest: "/etc/bashrc"
        line: "export EDITOR=/bin/vi"
        state: "present"
        backup: "yes"
        
    - name: "add line to /etc/profile"
      lineinfile:
        dest: "/etc/profile"
        line: "export EDITOR=/bin/vi"
        state: "present"
        backup: "yes"
