- name: copy files to another server
  hosts: all
  gather_facts: true
  become: true
  sudo: yes
  tasks:
  - copy:
      src: /home/faridarjmand/script.sh
      dest: /export/home/faridarjmand/
      mode: 0700
      owner: faridarjmand
      group: devops
      force: true
