---
- hosts: all
  user: ansible
  tasks:
    - name: script
      script: /root/test.sh
      register: script
    - debug: msg="{{ script.stdout }}"

    - name: script
      script: /home/script/ip.sh {{inventory_hostname}}
