---
- hosts: all
  user: root
  sudo: no

  #Define user and password variables
  vars:
    - password : arjmand
    - user : farid
    - group: root

  # Define task to add user
  tasks:
    - name: add group
      group: name={{ group }} state=present

    - name: delete group
      group: name={{ group }} state=absent

    - name: add user
      action: user name={{ user }} password={{ password }} home=/home/{{ user }} group={{ group }} shell=/bin/bash update_password=always state=present
      #user: name={{ items }} password={{ password }} group={{ group }} home=/home/{{ items }} shell=/bin/bash update_password=on_create state=present
      tags:
        - user
      with_items:
       - arj1

    - name: delete user
      user: name={{ user }} state=absent remove=yes

    - name: apply password policies to support users
      shell: passwd -x 30 {{ user }}; chage -d 0 {{ user }}
      
    - name: lock users
      shell: passwd -u {{ user }}
      
    - name: lock users
      shell: passwd -l {{ user }}
      register: lock
    - debug: msg="{{ lock.stdout_lines }}"
    
    - name: password change force
      shell: passwd -f {{ user }}
      
    - name: password change force
      shell: chage -d 0 {{ user }}
      
    - name: change expiration
      shell: passwd -x -1 {{ user }}
      
    - name: apply password policies to support users
      shell: passwd -x 30 {{ item }}; passwd -f {{ item }}
   
    - name: change expiration
      shell: chage -d -1 {{ user }}
    
    - name: changepass
      user: name={{ user }} password={{ password }} update_password=always
