- name: print out hosts architectures
  hosts: ALL
  gather_facts: true
  tasks:
  - debug: var=ansible_architecture
  - name: show just x86_64
    shell: echo "hi x86_64"
    when: ansible_architecture == "x86_64"
